// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package meta

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ColumnDef) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Type":
			{
				var zb0002 int
				zb0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ColumnType(zb0002)
			}
		case "NotNull":
			z.NotNull, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "NotNull")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ColumnDef) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Name"
	err = en.Append(0x83, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "Type"
	err = en.Append(0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(int(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "NotNull"
	err = en.Append(0xa7, 0x4e, 0x6f, 0x74, 0x4e, 0x75, 0x6c, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteBool(z.NotNull)
	if err != nil {
		err = msgp.WrapError(err, "NotNull")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ColumnDef) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Name"
	o = append(o, 0x83, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "Type"
	o = append(o, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt(o, int(z.Type))
	// string "NotNull"
	o = append(o, 0xa7, 0x4e, 0x6f, 0x74, 0x4e, 0x75, 0x6c, 0x6c)
	o = msgp.AppendBool(o, z.NotNull)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ColumnDef) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Type":
			{
				var zb0002 int
				zb0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ColumnType(zb0002)
			}
		case "NotNull":
			z.NotNull, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NotNull")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ColumnDef) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.IntSize + 8 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ColumnType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ColumnType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ColumnType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ColumnType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ColumnType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ColumnType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ColumnType) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *DDLJob) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "Index":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Index")
					return
				}
				z.Index = nil
			} else {
				if z.Index == nil {
					z.Index = new(IndexDef)
				}
				err = z.Index.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Index")
					return
				}
			}
		case "Cursor":
			z.Cursor, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Cursor")
				return
			}
		case "Started":
			z.Started, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Started")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DDLJob) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Type"
	err = en.Append(0x84, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "Index"
	err = en.Append(0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	if z.Index == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Index.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Index")
			return
		}
	}
	// write "Cursor"
	err = en.Append(0xa6, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Cursor)
	if err != nil {
		err = msgp.WrapError(err, "Cursor")
		return
	}
	// write "Started"
	err = en.Append(0xa7, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Started)
	if err != nil {
		err = msgp.WrapError(err, "Started")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DDLJob) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Type"
	o = append(o, 0x84, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "Index"
	o = append(o, 0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if z.Index == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Index.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Index")
			return
		}
	}
	// string "Cursor"
	o = append(o, 0xa6, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72)
	o = msgp.AppendInt(o, z.Cursor)
	// string "Started"
	o = append(o, 0xa7, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64)
	o = msgp.AppendInt64(o, z.Started)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DDLJob) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "Index":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Index = nil
			} else {
				if z.Index == nil {
					z.Index = new(IndexDef)
				}
				bts, err = z.Index.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Index")
					return
				}
			}
		case "Cursor":
			z.Cursor, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cursor")
				return
			}
		case "Started":
			z.Started, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Started")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DDLJob) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Type) + 6
	if z.Index == nil {
		s += msgp.NilSize
	} else {
		s += z.Index.Msgsize()
	}
	s += 7 + msgp.IntSize + 8 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *IndexDef) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Columns":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]string, zb0002)
			}
			for za0001 := range z.Columns {
				z.Columns[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "Kind":
			{
				var zb0003 int
				zb0003, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Kind")
					return
				}
				z.Kind = IndexKind(zb0003)
			}
		case "Covering":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Covering")
				return
			}
			if cap(z.Covering) >= int(zb0004) {
				z.Covering = (z.Covering)[:zb0004]
			} else {
				z.Covering = make([]string, zb0004)
			}
			for za0002 := range z.Covering {
				z.Covering[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Covering", za0002)
					return
				}
			}
		case "Async":
			z.Async, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Async")
				return
			}
		case "PrefixCopy":
			z.PrefixCopy, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "PrefixCopy")
				return
			}
		case "Building":
			z.Building, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Building")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *IndexDef) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "ID"
	err = en.Append(0x87, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "Columns"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Columns)))
	if err != nil {
		err = msgp.WrapError(err, "Columns")
		return
	}
	for za0001 := range z.Columns {
		err = en.WriteString(z.Columns[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Columns", za0001)
			return
		}
	}
	// write "Kind"
	err = en.Append(0xa4, 0x4b, 0x69, 0x6e, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt(int(z.Kind))
	if err != nil {
		err = msgp.WrapError(err, "Kind")
		return
	}
	// write "Covering"
	err = en.Append(0xa8, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Covering)))
	if err != nil {
		err = msgp.WrapError(err, "Covering")
		return
	}
	for za0002 := range z.Covering {
		err = en.WriteString(z.Covering[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Covering", za0002)
			return
		}
	}
	// write "Async"
	err = en.Append(0xa5, 0x41, 0x73, 0x79, 0x6e, 0x63)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Async)
	if err != nil {
		err = msgp.WrapError(err, "Async")
		return
	}
	// write "PrefixCopy"
	err = en.Append(0xaa, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x43, 0x6f, 0x70, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBool(z.PrefixCopy)
	if err != nil {
		err = msgp.WrapError(err, "PrefixCopy")
		return
	}
	// write "Building"
	err = en.Append(0xa8, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Building)
	if err != nil {
		err = msgp.WrapError(err, "Building")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *IndexDef) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "ID"
	o = append(o, 0x87, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "Columns"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Columns)))
	for za0001 := range z.Columns {
		o = msgp.AppendString(o, z.Columns[za0001])
	}
	// string "Kind"
	o = append(o, 0xa4, 0x4b, 0x69, 0x6e, 0x64)
	o = msgp.AppendInt(o, int(z.Kind))
	// string "Covering"
	o = append(o, 0xa8, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x69, 0x6e, 0x67)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Covering)))
	for za0002 := range z.Covering {
		o = msgp.AppendString(o, z.Covering[za0002])
	}
	// string "Async"
	o = append(o, 0xa5, 0x41, 0x73, 0x79, 0x6e, 0x63)
	o = msgp.AppendBool(o, z.Async)
	// string "PrefixCopy"
	o = append(o, 0xaa, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x43, 0x6f, 0x70, 0x79)
	o = msgp.AppendBool(o, z.PrefixCopy)
	// string "Building"
	o = append(o, 0xa8, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67)
	o = msgp.AppendBool(o, z.Building)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *IndexDef) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "Columns":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]string, zb0002)
			}
			for za0001 := range z.Columns {
				z.Columns[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "Kind":
			{
				var zb0003 int
				zb0003, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Kind")
					return
				}
				z.Kind = IndexKind(zb0003)
			}
		case "Covering":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Covering")
				return
			}
			if cap(z.Covering) >= int(zb0004) {
				z.Covering = (z.Covering)[:zb0004]
			} else {
				z.Covering = make([]string, zb0004)
			}
			for za0002 := range z.Covering {
				z.Covering[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Covering", za0002)
					return
				}
			}
		case "Async":
			z.Async, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Async")
				return
			}
		case "PrefixCopy":
			z.PrefixCopy, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PrefixCopy")
				return
			}
		case "Building":
			z.Building, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Building")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *IndexDef) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Columns {
		s += msgp.StringPrefixSize + len(z.Columns[za0001])
	}
	s += 5 + msgp.IntSize + 9 + msgp.ArrayHeaderSize
	for za0002 := range z.Covering {
		s += msgp.StringPrefixSize + len(z.Covering[za0002])
	}
	s += 6 + msgp.BoolSize + 11 + msgp.BoolSize + 9 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *IndexKind) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int
		zb0001, err = dc.ReadInt()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = IndexKind(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z IndexKind) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt(int(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z IndexKind) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *IndexKind) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int
		zb0001, bts, err = msgp.ReadIntBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = IndexKind(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z IndexKind) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TableDef) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Columns":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]ColumnDef, zb0002)
			}
			for za0001 := range z.Columns {
				err = z.Columns[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "PK":
			z.PK, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "Indexes":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Indexes")
				return
			}
			if cap(z.Indexes) >= int(zb0003) {
				z.Indexes = (z.Indexes)[:zb0003]
			} else {
				z.Indexes = make([]IndexDef, zb0003)
			}
			for za0002 := range z.Indexes {
				err = z.Indexes[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Indexes", za0002)
					return
				}
			}
		case "DefaultTTL":
			z.DefaultTTL, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DefaultTTL")
				return
			}
		case "MaxRowBytes":
			z.MaxRowBytes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MaxRowBytes")
				return
			}
		case "ExpectedRows":
			z.ExpectedRows, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ExpectedRows")
				return
			}
		case "ExpShards":
			z.ExpShards, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "ExpShards")
				return
			}
		case "Dimension":
			z.Dimension, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Dimension")
				return
			}
		case "AutoIncrColumn":
			z.AutoIncrColumn, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AutoIncrColumn")
				return
			}
		case "Ver":
			z.Ver, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Ver")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TableDef) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "Name"
	err = en.Append(0x8b, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "Columns"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Columns)))
	if err != nil {
		err = msgp.WrapError(err, "Columns")
		return
	}
	for za0001 := range z.Columns {
		err = z.Columns[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Columns", za0001)
			return
		}
	}
	// write "PK"
	err = en.Append(0xa2, 0x50, 0x4b)
	if err != nil {
		return
	}
	err = en.WriteString(z.PK)
	if err != nil {
		err = msgp.WrapError(err, "PK")
		return
	}
	// write "Indexes"
	err = en.Append(0xa7, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Indexes)))
	if err != nil {
		err = msgp.WrapError(err, "Indexes")
		return
	}
	for za0002 := range z.Indexes {
		err = z.Indexes[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Indexes", za0002)
			return
		}
	}
	// write "DefaultTTL"
	err = en.Append(0xaa, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.DefaultTTL)
	if err != nil {
		err = msgp.WrapError(err, "DefaultTTL")
		return
	}
	// write "MaxRowBytes"
	err = en.Append(0xab, 0x4d, 0x61, 0x78, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MaxRowBytes)
	if err != nil {
		err = msgp.WrapError(err, "MaxRowBytes")
		return
	}
	// write "ExpectedRows"
	err = en.Append(0xac, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.ExpectedRows)
	if err != nil {
		err = msgp.WrapError(err, "ExpectedRows")
		return
	}
	// write "ExpShards"
	err = en.Append(0xa9, 0x45, 0x78, 0x70, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.ExpShards)
	if err != nil {
		err = msgp.WrapError(err, "ExpShards")
		return
	}
	// write "Dimension"
	err = en.Append(0xa9, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Dimension)
	if err != nil {
		err = msgp.WrapError(err, "Dimension")
		return
	}
	// write "AutoIncrColumn"
	err = en.Append(0xae, 0x41, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.AutoIncrColumn)
	if err != nil {
		err = msgp.WrapError(err, "AutoIncrColumn")
		return
	}
	// write "Ver"
	err = en.Append(0xa3, 0x56, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Ver)
	if err != nil {
		err = msgp.WrapError(err, "Ver")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TableDef) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "Name"
	o = append(o, 0x8b, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "Columns"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Columns)))
	for za0001 := range z.Columns {
		o, err = z.Columns[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Columns", za0001)
			return
		}
	}
	// string "PK"
	o = append(o, 0xa2, 0x50, 0x4b)
	o = msgp.AppendString(o, z.PK)
	// string "Indexes"
	o = append(o, 0xa7, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Indexes)))
	for za0002 := range z.Indexes {
		o, err = z.Indexes[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Indexes", za0002)
			return
		}
	}
	// string "DefaultTTL"
	o = append(o, 0xaa, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c)
	o = msgp.AppendInt64(o, z.DefaultTTL)
	// string "MaxRowBytes"
	o = append(o, 0xab, 0x4d, 0x61, 0x78, 0x52, 0x6f, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendInt(o, z.MaxRowBytes)
	// string "ExpectedRows"
	o = append(o, 0xac, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73)
	o = msgp.AppendString(o, z.ExpectedRows)
	// string "ExpShards"
	o = append(o, 0xa9, 0x45, 0x78, 0x70, 0x53, 0x68, 0x61, 0x72, 0x64, 0x73)
	o = msgp.AppendInt(o, z.ExpShards)
	// string "Dimension"
	o = append(o, 0xa9, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendBool(o, z.Dimension)
	// string "AutoIncrColumn"
	o = append(o, 0xae, 0x41, 0x75, 0x74, 0x6f, 0x49, 0x6e, 0x63, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e)
	o = msgp.AppendString(o, z.AutoIncrColumn)
	// string "Ver"
	o = append(o, 0xa3, 0x56, 0x65, 0x72)
	o = msgp.AppendUint64(o, z.Ver)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TableDef) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Columns":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Columns")
				return
			}
			if cap(z.Columns) >= int(zb0002) {
				z.Columns = (z.Columns)[:zb0002]
			} else {
				z.Columns = make([]ColumnDef, zb0002)
			}
			for za0001 := range z.Columns {
				bts, err = z.Columns[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Columns", za0001)
					return
				}
			}
		case "PK":
			z.PK, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PK")
				return
			}
		case "Indexes":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Indexes")
				return
			}
			if cap(z.Indexes) >= int(zb0003) {
				z.Indexes = (z.Indexes)[:zb0003]
			} else {
				z.Indexes = make([]IndexDef, zb0003)
			}
			for za0002 := range z.Indexes {
				bts, err = z.Indexes[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Indexes", za0002)
					return
				}
			}
		case "DefaultTTL":
			z.DefaultTTL, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DefaultTTL")
				return
			}
		case "MaxRowBytes":
			z.MaxRowBytes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxRowBytes")
				return
			}
		case "ExpectedRows":
			z.ExpectedRows, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpectedRows")
				return
			}
		case "ExpShards":
			z.ExpShards, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpShards")
				return
			}
		case "Dimension":
			z.Dimension, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Dimension")
				return
			}
		case "AutoIncrColumn":
			z.AutoIncrColumn, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AutoIncrColumn")
				return
			}
		case "Ver":
			z.Ver, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ver")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TableDef) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Columns {
		s += z.Columns[za0001].Msgsize()
	}
	s += 3 + msgp.StringPrefixSize + len(z.PK) + 8 + msgp.ArrayHeaderSize
	for za0002 := range z.Indexes {
		s += z.Indexes[za0002].Msgsize()
	}
	s += 11 + msgp.Int64Size + 12 + msgp.IntSize + 13 + msgp.StringPrefixSize + len(z.ExpectedRows) + 10 + msgp.IntSize + 10 + msgp.BoolSize + 15 + msgp.StringPrefixSize + len(z.AutoIncrColumn) + 4 + msgp.Uint64Size
	return
}
