// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"kidb"
	"kidb/gateway"
)

// Injectors from wire.go:

// InitializeServer 生产装配的唯一入口（wire 编译期生成 wire_gen.go，
// 入库；改动 provider 后 `go generate ./di` 重新生成）。
func InitializeServer(boot kidb.Bootstrap) (*gateway.Server, error) {
	kvClient := ProvideClient(boot)
	kernel, err := ProvideKernel(kvClient, boot)
	if err != nil {
		return nil, err
	}
	registry := ProvideScripts(kernel)
	catalogStore := ProvideCatalogStore(kvClient, registry)
	catalogCache := ProvideCatalogCache(catalogStore)
	metrics := ProvideMetrics()
	recorder := ProvideTelemetry(kvClient)
	store := ProvideBucketMap(kvClient, registry)
	l4Manager := ProvideL4(kvClient, registry)
	shardedCache := ProvideNearCache()
	executor := ProvideExecutor(kvClient, registry, metrics, recorder, store, l4Manager, shardedCache)
	guard := ProvideGuard(kvClient, registry, store)
	deps := ProvideEngineDeps(kvClient, registry, catalogStore, catalogCache, executor, guard, metrics)
	roles := ProvideRoles(boot, kvClient, registry, catalogStore, catalogCache, executor, store, guard)
	configStore := ProvideConfigStore(kvClient, registry)
	server, err := gateway.NewServer(deps, boot, roles, configStore)
	if err != nil {
		return nil, err
	}
	return server, nil
}
