// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package bucketmap

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Doc) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Version":
			z.Version, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Next":
			z.Next, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Next")
				return
			}
		case "Eq":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Eq")
				return
			}
			if z.Eq == nil {
				z.Eq = make(map[string]*EqEntry, zb0002)
			} else if len(z.Eq) > 0 {
				clear(z.Eq)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Eq")
					return
				}
				var za0002 *EqEntry
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Eq", za0001)
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(EqEntry)
					}
					err = za0002.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Eq", za0001)
						return
					}
				}
				z.Eq[za0001] = za0002
			}
		case "Ranges":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Ranges")
				return
			}
			if cap(z.Ranges) >= int(zb0003) {
				z.Ranges = (z.Ranges)[:zb0003]
			} else {
				z.Ranges = make([]RangeBucket, zb0003)
			}
			for za0003 := range z.Ranges {
				err = z.Ranges[za0003].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Ranges", za0003)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Doc) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Version"
	err = en.Append(0x84, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "Next"
	err = en.Append(0xa4, 0x4e, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Next)
	if err != nil {
		err = msgp.WrapError(err, "Next")
		return
	}
	// write "Eq"
	err = en.Append(0xa2, 0x45, 0x71)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Eq)))
	if err != nil {
		err = msgp.WrapError(err, "Eq")
		return
	}
	for za0001, za0002 := range z.Eq {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Eq")
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0002.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Eq", za0001)
				return
			}
		}
	}
	// write "Ranges"
	err = en.Append(0xa6, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Ranges)))
	if err != nil {
		err = msgp.WrapError(err, "Ranges")
		return
	}
	for za0003 := range z.Ranges {
		err = z.Ranges[za0003].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Ranges", za0003)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Doc) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Version"
	o = append(o, 0x84, 0xa7, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint64(o, z.Version)
	// string "Next"
	o = append(o, 0xa4, 0x4e, 0x65, 0x78, 0x74)
	o = msgp.AppendInt(o, z.Next)
	// string "Eq"
	o = append(o, 0xa2, 0x45, 0x71)
	o = msgp.AppendMapHeader(o, uint32(len(z.Eq)))
	for za0001, za0002 := range z.Eq {
		o = msgp.AppendString(o, za0001)
		if za0002 == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = za0002.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Eq", za0001)
				return
			}
		}
	}
	// string "Ranges"
	o = append(o, 0xa6, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Ranges)))
	for za0003 := range z.Ranges {
		o, err = z.Ranges[za0003].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Ranges", za0003)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Doc) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Version":
			z.Version, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "Next":
			z.Next, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Next")
				return
			}
		case "Eq":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Eq")
				return
			}
			if z.Eq == nil {
				z.Eq = make(map[string]*EqEntry, zb0002)
			} else if len(z.Eq) > 0 {
				clear(z.Eq)
			}
			for zb0002 > 0 {
				var za0002 *EqEntry
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Eq")
					return
				}
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(EqEntry)
					}
					bts, err = za0002.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Eq", za0001)
						return
					}
				}
				z.Eq[za0001] = za0002
			}
		case "Ranges":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Ranges")
				return
			}
			if cap(z.Ranges) >= int(zb0003) {
				z.Ranges = (z.Ranges)[:zb0003]
			} else {
				z.Ranges = make([]RangeBucket, zb0003)
			}
			for za0003 := range z.Ranges {
				bts, err = z.Ranges[za0003].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Ranges", za0003)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Doc) Msgsize() (s int) {
	s = 1 + 8 + msgp.Uint64Size + 5 + msgp.IntSize + 3 + msgp.MapHeaderSize
	if z.Eq != nil {
		for za0001, za0002 := range z.Eq {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += za0002.Msgsize()
			}
		}
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0003 := range z.Ranges {
		s += z.Ranges[za0003].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EqEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Buckets":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Buckets")
				return
			}
			if cap(z.Buckets) >= int(zb0002) {
				z.Buckets = (z.Buckets)[:zb0002]
			} else {
				z.Buckets = make([]int, zb0002)
			}
			for za0001 := range z.Buckets {
				z.Buckets[za0001], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Buckets", za0001)
					return
				}
			}
		case "Split":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Split")
					return
				}
				z.Split = nil
			} else {
				if z.Split == nil {
					z.Split = new(SplitInfo)
				}
				err = z.Split.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Split")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *EqEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Buckets"
	err = en.Append(0x82, 0xa7, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Buckets)))
	if err != nil {
		err = msgp.WrapError(err, "Buckets")
		return
	}
	for za0001 := range z.Buckets {
		err = en.WriteInt(z.Buckets[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Buckets", za0001)
			return
		}
	}
	// write "Split"
	err = en.Append(0xa5, 0x53, 0x70, 0x6c, 0x69, 0x74)
	if err != nil {
		return
	}
	if z.Split == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Split.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Split")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *EqEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Buckets"
	o = append(o, 0x82, 0xa7, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Buckets)))
	for za0001 := range z.Buckets {
		o = msgp.AppendInt(o, z.Buckets[za0001])
	}
	// string "Split"
	o = append(o, 0xa5, 0x53, 0x70, 0x6c, 0x69, 0x74)
	if z.Split == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Split.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Split")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EqEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Buckets":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Buckets")
				return
			}
			if cap(z.Buckets) >= int(zb0002) {
				z.Buckets = (z.Buckets)[:zb0002]
			} else {
				z.Buckets = make([]int, zb0002)
			}
			for za0001 := range z.Buckets {
				z.Buckets[za0001], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Buckets", za0001)
					return
				}
			}
		case "Split":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Split = nil
			} else {
				if z.Split == nil {
					z.Split = new(SplitInfo)
				}
				bts, err = z.Split.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Split")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *EqEntry) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize + (len(z.Buckets) * (msgp.IntSize)) + 6
	if z.Split == nil {
		s += msgp.NilSize
	} else {
		s += z.Split.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RangeBucket) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Idx":
			z.Idx, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Idx")
				return
			}
		case "Lo":
			z.Lo, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Lo")
				return
			}
		case "Hi":
			z.Hi, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hi")
				return
			}
		case "State":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = State(zb0002)
			}
		case "Children":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Children")
				return
			}
			if cap(z.Children) >= int(zb0003) {
				z.Children = (z.Children)[:zb0003]
			} else {
				z.Children = make([]RangeBucket, zb0003)
			}
			for za0001 := range z.Children {
				err = z.Children[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Children", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RangeBucket) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Idx"
	err = en.Append(0x85, 0xa3, 0x49, 0x64, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Idx)
	if err != nil {
		err = msgp.WrapError(err, "Idx")
		return
	}
	// write "Lo"
	err = en.Append(0xa2, 0x4c, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteString(z.Lo)
	if err != nil {
		err = msgp.WrapError(err, "Lo")
		return
	}
	// write "Hi"
	err = en.Append(0xa2, 0x48, 0x69)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hi)
	if err != nil {
		err = msgp.WrapError(err, "Hi")
		return
	}
	// write "State"
	err = en.Append(0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.State))
	if err != nil {
		err = msgp.WrapError(err, "State")
		return
	}
	// write "Children"
	err = en.Append(0xa8, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Children)))
	if err != nil {
		err = msgp.WrapError(err, "Children")
		return
	}
	for za0001 := range z.Children {
		err = z.Children[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Children", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RangeBucket) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Idx"
	o = append(o, 0x85, 0xa3, 0x49, 0x64, 0x78)
	o = msgp.AppendInt(o, z.Idx)
	// string "Lo"
	o = append(o, 0xa2, 0x4c, 0x6f)
	o = msgp.AppendString(o, z.Lo)
	// string "Hi"
	o = append(o, 0xa2, 0x48, 0x69)
	o = msgp.AppendString(o, z.Hi)
	// string "State"
	o = append(o, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, string(z.State))
	// string "Children"
	o = append(o, 0xa8, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Children)))
	for za0001 := range z.Children {
		o, err = z.Children[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Children", za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RangeBucket) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Idx":
			z.Idx, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Idx")
				return
			}
		case "Lo":
			z.Lo, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Lo")
				return
			}
		case "Hi":
			z.Hi, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hi")
				return
			}
		case "State":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = State(zb0002)
			}
		case "Children":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Children")
				return
			}
			if cap(z.Children) >= int(zb0003) {
				z.Children = (z.Children)[:zb0003]
			} else {
				z.Children = make([]RangeBucket, zb0003)
			}
			for za0001 := range z.Children {
				bts, err = z.Children[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Children", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RangeBucket) Msgsize() (s int) {
	s = 1 + 4 + msgp.IntSize + 3 + msgp.StringPrefixSize + len(z.Lo) + 3 + msgp.StringPrefixSize + len(z.Hi) + 6 + msgp.StringPrefixSize + len(string(z.State)) + 9 + msgp.ArrayHeaderSize
	for za0001 := range z.Children {
		s += z.Children[za0001].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SplitInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "State":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = State(zb0002)
			}
		case "Parents":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Parents")
				return
			}
			if cap(z.Parents) >= int(zb0003) {
				z.Parents = (z.Parents)[:zb0003]
			} else {
				z.Parents = make([]int, zb0003)
			}
			for za0001 := range z.Parents {
				z.Parents[za0001], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Parents", za0001)
					return
				}
			}
		case "Children":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Children")
				return
			}
			if cap(z.Children) >= int(zb0004) {
				z.Children = (z.Children)[:zb0004]
			} else {
				z.Children = make([]int, zb0004)
			}
			for za0002 := range z.Children {
				z.Children[za0002], err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Children", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SplitInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "State"
	err = en.Append(0x83, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.State))
	if err != nil {
		err = msgp.WrapError(err, "State")
		return
	}
	// write "Parents"
	err = en.Append(0xa7, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Parents)))
	if err != nil {
		err = msgp.WrapError(err, "Parents")
		return
	}
	for za0001 := range z.Parents {
		err = en.WriteInt(z.Parents[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Parents", za0001)
			return
		}
	}
	// write "Children"
	err = en.Append(0xa8, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Children)))
	if err != nil {
		err = msgp.WrapError(err, "Children")
		return
	}
	for za0002 := range z.Children {
		err = en.WriteInt(z.Children[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Children", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SplitInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "State"
	o = append(o, 0x83, 0xa5, 0x53, 0x74, 0x61, 0x74, 0x65)
	o = msgp.AppendString(o, string(z.State))
	// string "Parents"
	o = append(o, 0xa7, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Parents)))
	for za0001 := range z.Parents {
		o = msgp.AppendInt(o, z.Parents[za0001])
	}
	// string "Children"
	o = append(o, 0xa8, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Children)))
	for za0002 := range z.Children {
		o = msgp.AppendInt(o, z.Children[za0002])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SplitInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "State":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "State")
					return
				}
				z.State = State(zb0002)
			}
		case "Parents":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Parents")
				return
			}
			if cap(z.Parents) >= int(zb0003) {
				z.Parents = (z.Parents)[:zb0003]
			} else {
				z.Parents = make([]int, zb0003)
			}
			for za0001 := range z.Parents {
				z.Parents[za0001], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Parents", za0001)
					return
				}
			}
		case "Children":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Children")
				return
			}
			if cap(z.Children) >= int(zb0004) {
				z.Children = (z.Children)[:zb0004]
			} else {
				z.Children = make([]int, zb0004)
			}
			for za0002 := range z.Children {
				z.Children[za0002], bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Children", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SplitInfo) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(string(z.State)) + 8 + msgp.ArrayHeaderSize + (len(z.Parents) * (msgp.IntSize)) + 9 + msgp.ArrayHeaderSize + (len(z.Children) * (msgp.IntSize))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *State) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = State(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z State) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z State) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *State) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = State(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z State) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}
